import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { TodoProvider } from "@/context/todoContext";
import { ThemeProvider } from "@/context/themeContext";
import { ModalProvider } from "@/context/ModalContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ModalProvider>
        <ThemeProvider>
          <TodoProvider>
            <body className={`${inter.className}`}>{children}</body>
          </TodoProvider>
        </ThemeProvider>
      </ModalProvider>
    </html>
  );
}
